import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import CartContext from "@/context/CartContext";
import AuthProviders from "@/AuthProviders/AuthProviders";
const inter = Inter({ subsets: ["latin"] });
// import { usePathname } from "next/navigation";
export const metadata = {
  title: "Detrator Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const pathname = usePathname();
  // if (pathname === "/login" || pathname === "/register") {
  //   return (
  //     <html lang="en">
  //       <body className={inter.className}>
  //         <main>{children}</main>
  //       </body>
  //     </html>
  //   );
  // }
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContext>
          <AuthProviders>
            <Header />
            <main>{children}</main>
          </AuthProviders>
        </CartContext>
      </body>
    </html>
  );
}
