import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import CartContext from "@/context/CartContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContext>
          <Header />
          <main>{children}</main>
        </CartContext>
      </body>
    </html>
  );
}
